# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  Name: 'Ukrainian Unicode'
  
jobs:
  build:
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # create dmg
      - name: hdiutil
        run: hdiutil create "${{ env.Name }} ${{ github.event.release.tag_name }}.dmg" -volname "${{ env.Name }} ${{ github.event.release.tag_name }}" -fs HFS+ -srcfolder .

      # upload dmg
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: "${{ env.Name }} ${{ github.event.release.tag_name }}.dmg"
          path: '*.dmg'
